title: Gyöngyösi Gábor
description: IT Systems Integrator | Open Source Developer
gravatar_email: megvadulthangya@gmail.com
author:
  name: Gyöngyösi Gábor
  email: 'gyongyosigabor@gshoots.hu'
metadata:
    description: 'Gyöngyösi Gábor önéletrajza - IT Systems Integrator, Open Source Developer & Hardware Specialist.'

website: "links.gshoots.hu"

address:
    - line: "Budapest"
    - line: "Hungary"

contact: 
    - line: "gyongyosigabor@gshoots.hu"
    - line: "+36 50 105 4964"
    - line: "github.com/megvadulthangya"